### ISSUE TITLE
Remove Application - Client ID/Secret

### ISSUE THREAD

**Issue by maxcell** [chardane/ClarifaiRuby#14]
@chardane: [Github doesn't lie](https://github.com/chardane/ClarifaiRuby/blame/master/spec/spec_helper.rb#L19-L20)

**Comment by cassidoo** [comment]
One thing that would help protect your account here is that once this is removed: actually change your own personal ID/Secret by deleting that application on your account at developer.clarifai.com, and making a new one (which will have different credentials), so that nobody can find your old keys and use them.

**Comment by maxcell** [comment]
Perfect advice as always. @chardane will need to make that stuff happen. Fortunately we have already removed the Client ID/Secret from the files but of course history is still a thing :)
